"""Canonical column schema shared by all formatted-media outputs."""

TEMPLATE_COLUMNS = [
    "Region",
    "Market",
    "BU",
    "Customer",
    "Date",
    "Duration",
    "Media",
    "Platform",
    "Advertiser Currency",
    "Final URL",
    "Item (Summary of filter)",
    "Account name",
    "Campaign name",
    "Campaign Objective",
    "Campaign Free Form",
    "Adset name",
    "Audience",
    "Adset Free Form",
    "Message Type",
    "Ad Free Form",
    "Adset MD",
    "Product",
    "Channel",
    "InName Site",
    "Campaign Type",
    "Buying Type",
    "Placement",
    "SEM Status",
    "Reach",
    "Impressions",
    "Clicks (all)",
    "Frequency",
    "Link clicks (Web Clicks)",
    "Spent (TWD)",
    "Purchases conversion value",
    "Conversions",
    "Conversion Value",
    "MV>5",
    "Views",
    '3" Video Views',
    '15" Video Views (ThruPlays)',
    "TrueView: Views",
    "Video played to 25%",
    "Video played to 50%",
    "Video played to 75%",
    "Video played to 100%",
    "Fan page like",
    "Page Likes or followers",
    "Post comments",
    "Post engagements",
    "Post reactions",
    "Post shares",
    "Photo Views",
    "Post Saves",
    "Adds to cart",
    "Purchases",
    "Revenue",
    "Sales Engagement",
    "Purchase ROAS",
    "Quality Score",
    "Leads",
    "Actions",
    "View-through conversion",
    "Clicks conversion",
    "View conversion",
    "User number",
    "Total PPL",
    "New user",
    "Working session",
    "Bounce Rate",
    "Avg engagement time per session",
    "Avg Working session time",
    "GA Session name",
    "GA Session Type",
    "GA Session Qty",
    "TVR",
    "10 Second TVR",
    "Reach 000s",
]
